### ISSUE TITLE
你好，我想部署你的项目，但是遇到下面这个问题，请问应该怎么解决呀

### ISSUE THREAD

**Issue by SH-AJ** [Chinoholo0807/blockchain-based-federate-learning#1]
Traceback (most recent call last):
  File "/home/li/brownieProject/client_module/invoker.py", line 3, in <module>
    from brownie import ModelTrain, Contract
ImportError: cannot import name 'ModelTrain'

**Comment by SH-AJ** [comment]
scripts 是不是需要 main()

**Comment by Chinoholo0807** [comment]
ImportError应该是你vscode/pycharm工作路径配置的问题，`scripts`的使用方法见federate_learning_with_blockchain\computing_market\helpful_cmd.md，是在brownie console中作为辅助脚本导入

**Comment by Trackatbar** [comment]
感谢哈，但是现在又报了这个错误，想问下这个该怎么解决呀
cs = ClusterSimulator('conf/cluster.yaml')
  File "<console>", line 2, in <module>
  File "/home/li/brownieProject/scripts/simulator.py", line 20, in __init__
  File "/home/li/brownieProject/scripts/helpful_scripts.py", line 5, in read_yaml
FileNotFoundError: [Errno 2] No such file or directory: 'conf/cluster.yaml'

**Comment by Trackatbar** [comment]
感谢哈，但是现在又报了这个错误，一直调试不好，想问下这个该怎么解决呀
>>> from scripts.simulator import ClusterSimulator
>>> cs = ClusterSimulator('conf/cluster.yaml')
  File "<console>", line 1, in <module>
  File "/home/li/brownieProject/scripts/simulator.py", line 22, in __init__
  File "/home/li/brownieProject/client_module/log.py", line 33, in init_logging
FileNotFoundError: [Errno 2] No such file or directory: '.\\reports\\logs/2023-01-08_21-42-48.log'

**Comment by SH-AJ** [comment]
感谢哈 已经跑通了，太厉害了 想问下有没有paper可以参考的呀！

**Comment by Wit199** [comment]
请问如何部署呀
